# Resolve fmt, Kineto, ITT, and GTest without requiring any particular host build.

set(_PROFILER_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(_profiler_third_party_root out_var)
  if(PROFILER_THIRD_PARTY_DIR)
    set(${out_var} "${PROFILER_THIRD_PARTY_DIR}" PARENT_SCOPE)
  elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/fmt/CMakeLists.txt")
    set(${out_var} "${CMAKE_CURRENT_SOURCE_DIR}/third_party" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(profiler_fetch_git name url tag dest_subdir)
  include(FetchContent)
  string(TOLOWER "${name}" _lc)
  FetchContent_Declare(
    ${name}
    GIT_REPOSITORY "${url}"
    GIT_TAG "${tag}"
    SOURCE_DIR "${_PROFILER_CMAKE_DIR}/../third_party/${dest_subdir}"
  )
  FetchContent_GetProperties(${name})
  if(NOT ${_lc}_POPULATED)
    FetchContent_Populate(${name})
  endif()
endfunction()

function(profiler_setup_fmt)
  if(TARGET Fmt::fmt OR TARGET fmt OR TARGET fmt::fmt)
    if(NOT TARGET fmt::fmt-header-only AND TARGET fmt)
      add_library(fmt::fmt-header-only ALIAS fmt)
    endif()
    return()
  endif()
  _profiler_third_party_root(_tp)
  if(_tp AND EXISTS "${_tp}/fmt/CMakeLists.txt")
    set(FMT_TEST OFF CACHE BOOL "" FORCE)
    set(FMT_DOC OFF CACHE BOOL "" FORCE)
    set(_profiler_fmt_shared "${BUILD_SHARED_LIBS}")
    set(BUILD_SHARED_LIBS OFF)
    add_subdirectory("${_tp}/fmt" "${CMAKE_BINARY_DIR}/_profiler_fmt" EXCLUDE_FROM_ALL)
    set(BUILD_SHARED_LIBS "${_profiler_fmt_shared}")
  else()
    profiler_fetch_git(fmt "https://github.com/fmtlib/fmt.git" "12.2.0" fmt)
    set(FMT_TEST OFF CACHE BOOL "" FORCE)
    set(FMT_DOC OFF CACHE BOOL "" FORCE)
    set(_profiler_fmt_shared "${BUILD_SHARED_LIBS}")
    set(BUILD_SHARED_LIBS OFF)
    add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/third_party/fmt"
                     "${CMAKE_BINARY_DIR}/_profiler_fmt" EXCLUDE_FROM_ALL)
    set(BUILD_SHARED_LIBS "${_profiler_fmt_shared}")
  endif()
  if(TARGET fmt)
    target_compile_definitions(fmt PUBLIC FMT_USE_CONSTEVAL=0)
    set_property(TARGET fmt PROPERTY POSITION_INDEPENDENT_CODE ON)
  endif()
  if(NOT TARGET fmt::fmt-header-only AND TARGET fmt)
    add_library(fmt::fmt-header-only ALIAS fmt)
  endif()
endfunction()

function(profiler_setup_kineto)
  if(TARGET Kineto::kineto OR TARGET kineto)
    if(NOT TARGET Kineto::kineto AND TARGET kineto)
      add_library(Kineto::kineto ALIAS kineto)
    endif()
    return()
  endif()
  _profiler_third_party_root(_tp)
  set(_kineto_src "")
  if(_tp AND EXISTS "${_tp}/kineto/libkineto/CMakeLists.txt")
    set(_kineto_src "${_tp}/kineto/libkineto")
    if(EXISTS "${_tp}/fmt")
      set(FMT_SOURCE_DIR "${_tp}/fmt" CACHE STRING "" FORCE)
    endif()
  else()
    profiler_fetch_git(
      kineto "https://github.com/pytorch/kineto.git"
      "eeaa4244e5f8e5f2690212c7c24e8b08061382d8" kineto
    )
    set(_kineto_src "${CMAKE_CURRENT_SOURCE_DIR}/third_party/kineto/libkineto")
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/fmt")
      set(FMT_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/fmt" CACHE STRING "" FORCE)
    endif()
  endif()

  set(KINETO_BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(KINETO_LIBRARY_TYPE "static" CACHE STRING "" FORCE)
  add_subdirectory("${_kineto_src}" "${CMAKE_BINARY_DIR}/_profiler_kineto" EXCLUDE_FROM_ALL)
  # Kineto defaults to header-only fmt, while Profiler links compiled fmt.
  # Mixing them produces duplicate fmt symbols under MSVC. Use the same
  # compiled target for Kineto's object libraries and their final archive.
  if(TARGET Fmt::fmt)
    set(_kineto_fmt_target Fmt::fmt)
  elseif(TARGET fmt::fmt)
    set(_kineto_fmt_target fmt::fmt)
  else()
    set(_kineto_fmt_target fmt)
  endif()
  foreach(_kineto_object_target kineto_base kineto_api)
    if(TARGET ${_kineto_object_target})
      get_target_property(_kineto_links ${_kineto_object_target} LINK_LIBRARIES)
      string(REPLACE "fmt::fmt-header-only" "${_kineto_fmt_target}"
             _kineto_links "${_kineto_links}")
      set_property(TARGET ${_kineto_object_target} PROPERTY LINK_LIBRARIES "${_kineto_links}")
    endif()
  endforeach()
  # $<TARGET_OBJECTS:...> does not propagate the object libraries' link dependencies.
  # Append properties directly: upstream uses different target_link_libraries
  # signatures for CUDA and ROCm, which cannot be mixed with another signature.
  set_property(TARGET kineto APPEND PROPERTY LINK_LIBRARIES
               $<BUILD_INTERFACE:${_kineto_fmt_target}>)
  set_property(TARGET kineto APPEND PROPERTY INTERFACE_LINK_LIBRARIES
               $<LINK_ONLY:$<BUILD_INTERFACE:${_kineto_fmt_target}>>)
  set(_fmt_kineto_compat "${_PROFILER_CMAKE_DIR}/fmt_kineto_compat.h")
  foreach(_kineto_target kineto kineto_base kineto_api)
    if(TARGET ${_kineto_target})
      set_property(TARGET ${_kineto_target} PROPERTY POSITION_INDEPENDENT_CODE ON)
      target_compile_definitions(${_kineto_target} PRIVATE FMT_USE_CONSTEVAL=0)
      if(EXISTS "${_fmt_kineto_compat}")
        if(MSVC)
          target_compile_options(${_kineto_target} PRIVATE "/FI${_fmt_kineto_compat}")
        else()
          target_compile_options(${_kineto_target} PRIVATE "-include" "${_fmt_kineto_compat}")
        endif()
      endif()
    endif()
  endforeach()
  if(TARGET kineto_base AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    if(MSVC)
      foreach(_kt kineto_base kineto_api)
        if(TARGET ${_kt})
          target_compile_options(${_kt} PRIVATE /clang:-O2)
        endif()
      endforeach()
    else()
      target_compile_options(kineto_base PRIVATE -O2)
    endif()
  endif()
  if(TARGET kineto)
    # libkineto puts public headers on kineto_base/kineto_api, not kineto.
    # Consumers that link kineto still need libkineto/include.
    target_include_directories(
      kineto PUBLIC $<BUILD_INTERFACE:${_kineto_src}/include>
                    $<BUILD_INTERFACE:${_kineto_src}/src>
    )
    if(NOT TARGET Kineto::kineto)
      add_library(Kineto::kineto ALIAS kineto)
    endif()
  endif()
endfunction()

function(profiler_setup_itt)
  if(TARGET Itt::itt)
    return()
  endif()
  _profiler_third_party_root(_tp)
  set(_itt "")
  if(_tp AND EXISTS "${_tp}/ittapi/CMakeLists.txt")
    set(_itt "${_tp}/ittapi")
  elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/ittapi/CMakeLists.txt")
    set(_itt "${CMAKE_CURRENT_SOURCE_DIR}/third_party/ittapi")
  else()
    profiler_fetch_git(ittapi "https://github.com/intel/ittapi.git" "v3.28.4" ittapi)
    set(_itt "${CMAKE_CURRENT_SOURCE_DIR}/third_party/ittapi")
  endif()
  if(EXISTS "${_itt}/CMakeLists.txt")
    add_subdirectory("${_itt}" "${CMAKE_BINARY_DIR}/_profiler_itt" EXCLUDE_FROM_ALL)
    if(TARGET ittnotify)
      set_property(TARGET ittnotify PROPERTY POSITION_INDEPENDENT_CODE ON)
      if(NOT TARGET Itt::itt)
        add_library(Itt::itt ALIAS ittnotify)
      endif()
    endif()
  endif()
endfunction()

function(profiler_setup_gtest)
  if(TARGET GTest::gtest_main OR TARGET gtest_main)
    if(TARGET gtest AND NOT TARGET GTest::gtest)
      add_library(GTest::gtest ALIAS gtest)
    endif()
    if(TARGET gtest_main AND NOT TARGET GTest::gtest_main)
      add_library(GTest::gtest_main ALIAS gtest_main)
    endif()
    return()
  endif()
  if(COMMAND profiler_host_add_googletest)
    profiler_host_add_googletest()
    return()
  endif()
  _profiler_third_party_root(_tp)
  if(_tp AND EXISTS "${_tp}/googletest/CMakeLists.txt")
    set(INSTALL_GTEST OFF CACHE BOOL "" FORCE)
    add_subdirectory("${_tp}/googletest" "${CMAKE_BINARY_DIR}/_profiler_gtest"
                     EXCLUDE_FROM_ALL)
  else()
    include(FetchContent)
    FetchContent_Declare(
      googletest
      GIT_REPOSITORY https://github.com/google/googletest.git
      GIT_TAG v1.18.0
    )
    set(INSTALL_GTEST OFF CACHE BOOL "" FORCE)
    FetchContent_MakeAvailable(googletest)
  endif()
  if(TARGET gtest AND NOT TARGET GTest::gtest)
    add_library(GTest::gtest ALIAS gtest)
  endif()
  if(TARGET gtest_main AND NOT TARGET GTest::gtest_main)
    add_library(GTest::gtest_main ALIAS gtest_main)
  endif()
endfunction()

function(profiler_setup_benchmark)
  if(TARGET benchmark::benchmark OR TARGET benchmark)
    if(TARGET benchmark AND NOT TARGET benchmark::benchmark)
      add_library(benchmark::benchmark ALIAS benchmark)
    endif()
    return()
  endif()
  _profiler_third_party_root(_tp)
  if(NOT _tp OR NOT EXISTS "${_tp}/benchmark/CMakeLists.txt")
    message(FATAL_ERROR
            "Google Benchmark is required for PROFILER_ENABLE_BENCHMARKS. "
            "Initialize third_party/benchmark with git submodule update --init --recursive.")
  endif()
  set(BENCHMARK_ENABLE_GTEST_TESTS OFF CACHE BOOL "" FORCE)
  set(BENCHMARK_ENABLE_TESTING OFF CACHE BOOL "" FORCE)
  set(BENCHMARK_ENABLE_INSTALL OFF CACHE BOOL "" FORCE)
  set(BENCHMARK_DOWNLOAD_DEPENDENCIES OFF CACHE BOOL "" FORCE)
  add_subdirectory("${_tp}/benchmark" "${CMAKE_BINARY_DIR}/_profiler_benchmark" EXCLUDE_FROM_ALL)
  if(TARGET benchmark AND NOT TARGET benchmark::benchmark)
    add_library(benchmark::benchmark ALIAS benchmark)
  endif()
endfunction()
