# Resolve fmt, Kineto, ITT, and GTest without requiring an XSigma tree.

function(_profiler_third_party_root out_var)
  if(PROFILER_THIRD_PARTY_DIR)
    set(${out_var} "${PROFILER_THIRD_PARTY_DIR}" PARENT_SCOPE)
  elseif(DEFINED XSIGMA_THIRDPARTY_DIR AND XSIGMA_THIRDPARTY_DIR)
    set(${out_var} "${XSIGMA_THIRDPARTY_DIR}" PARENT_SCOPE)
  elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/fmt/CMakeLists.txt")
    set(${out_var} "${CMAKE_CURRENT_SOURCE_DIR}/third_party" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(profiler_fetch_git name url tag dest_subdir)
  include(FetchContent)
  string(TOLOWER "${name}" _lc)
  FetchContent_Declare(
    ${name}
    GIT_REPOSITORY "${url}"
    GIT_TAG "${tag}"
    SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/${dest_subdir}"
  )
  FetchContent_GetProperties(${name})
  if(NOT ${_lc}_POPULATED)
    FetchContent_Populate(${name})
  endif()
endfunction()

function(profiler_setup_fmt)
  if(TARGET Fmt::fmt OR TARGET fmt OR TARGET fmt::fmt)
    return()
  endif()
  _profiler_third_party_root(_tp)
  if(_tp AND EXISTS "${_tp}/fmt/CMakeLists.txt")
    set(FMT_TEST OFF CACHE BOOL "" FORCE)
    set(FMT_DOC OFF CACHE BOOL "" FORCE)
    set(_profiler_fmt_shared "${BUILD_SHARED_LIBS}")
    set(BUILD_SHARED_LIBS OFF)
    add_subdirectory("${_tp}/fmt" "${CMAKE_BINARY_DIR}/_xsigma_profiler_fmt" EXCLUDE_FROM_ALL)
    set(BUILD_SHARED_LIBS "${_profiler_fmt_shared}")
  else()
    profiler_fetch_git(fmt "https://github.com/fmtlib/fmt.git" "11.0.2" fmt)
    set(FMT_TEST OFF CACHE BOOL "" FORCE)
    set(FMT_DOC OFF CACHE BOOL "" FORCE)
    set(_profiler_fmt_shared "${BUILD_SHARED_LIBS}")
    set(BUILD_SHARED_LIBS OFF)
    add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/third_party/fmt"
                     "${CMAKE_BINARY_DIR}/_xsigma_profiler_fmt" EXCLUDE_FROM_ALL)
    set(BUILD_SHARED_LIBS "${_profiler_fmt_shared}")
  endif()
endfunction()

function(profiler_setup_kineto)
  if(TARGET Kineto::kineto OR TARGET kineto)
    if(NOT TARGET Kineto::kineto AND TARGET kineto)
      add_library(Kineto::kineto ALIAS kineto)
    endif()
    return()
  endif()
  _profiler_third_party_root(_tp)
  set(_kineto_src "")
  if(_tp AND EXISTS "${_tp}/kineto/libkineto/CMakeLists.txt")
    set(_kineto_src "${_tp}/kineto/libkineto")
    if(EXISTS "${_tp}/fmt")
      set(FMT_SOURCE_DIR "${_tp}/fmt" CACHE STRING "" FORCE)
    endif()
  else()
    profiler_fetch_git(kineto "https://github.com/pytorch/kineto.git" "v0.4.0" kineto)
    set(_kineto_src "${CMAKE_CURRENT_SOURCE_DIR}/third_party/kineto/libkineto")
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/fmt")
      set(FMT_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/fmt" CACHE STRING "" FORCE)
    endif()
  endif()

  set(KINETO_BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(KINETO_LIBRARY_TYPE "static" CACHE STRING "" FORCE)
  add_subdirectory("${_kineto_src}" "${CMAKE_BINARY_DIR}/_xsigma_profiler_kineto" EXCLUDE_FROM_ALL)
  foreach(_kineto_target kineto kineto_base kineto_api)
    if(TARGET ${_kineto_target})
      set_property(TARGET ${_kineto_target} PROPERTY POSITION_INDEPENDENT_CODE ON)
    endif()
  endforeach()
  if(TARGET kineto_base AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    if(MSVC)
      foreach(_kt kineto_base kineto_api)
        if(TARGET ${_kt})
          target_compile_options(${_kt} PRIVATE /clang:-O2)
        endif()
      endforeach()
    else()
      target_compile_options(kineto_base PRIVATE -O2)
    endif()
  endif()
  if(TARGET kineto AND NOT TARGET Kineto::kineto)
    add_library(Kineto::kineto ALIAS kineto)
  endif()
endfunction()

function(profiler_setup_itt)
  if(TARGET Itt::itt)
    return()
  endif()
  _profiler_third_party_root(_tp)
  set(_itt "")
  if(_tp AND EXISTS "${_tp}/ittapi/CMakeLists.txt")
    set(_itt "${_tp}/ittapi")
  elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/ittapi/CMakeLists.txt")
    set(_itt "${CMAKE_CURRENT_SOURCE_DIR}/third_party/ittapi")
  else()
    profiler_fetch_git(ittapi "https://github.com/intel/ittapi.git" "v3.25.5" ittapi)
    set(_itt "${CMAKE_CURRENT_SOURCE_DIR}/third_party/ittapi")
  endif()
  if(EXISTS "${_itt}/CMakeLists.txt")
    add_subdirectory("${_itt}" "${CMAKE_BINARY_DIR}/_xsigma_profiler_itt" EXCLUDE_FROM_ALL)
    if(TARGET ittnotify AND NOT TARGET Itt::itt)
      add_library(Itt::itt ALIAS ittnotify)
    endif()
  endif()
endfunction()

function(profiler_setup_gtest)
  if(TARGET GTest::gtest OR TARGET Gtest::gtest OR TARGET gtest)
    if(TARGET gtest AND NOT TARGET GTest::gtest)
      add_library(GTest::gtest ALIAS gtest)
    endif()
    if(TARGET gtest_main AND NOT TARGET GTest::gtest_main)
      add_library(GTest::gtest_main ALIAS gtest_main)
    endif()
    if(TARGET GTest::gtest AND NOT TARGET Gtest::gtest)
      add_library(Gtest::gtest ALIAS GTest::gtest)
    endif()
    if(TARGET GTest::gtest_main AND NOT TARGET Gtest::gtest_main)
      add_library(Gtest::gtest_main ALIAS GTest::gtest_main)
    endif()
    return()
  endif()
  if(COMMAND xsigma_add_googletest)
    xsigma_add_googletest()
    return()
  endif()
  _profiler_third_party_root(_tp)
  if(_tp AND EXISTS "${_tp}/googletest/CMakeLists.txt")
    set(INSTALL_GTEST OFF CACHE BOOL "" FORCE)
    add_subdirectory("${_tp}/googletest" "${CMAKE_BINARY_DIR}/_xsigma_profiler_gtest"
                     EXCLUDE_FROM_ALL)
  else()
    include(FetchContent)
    FetchContent_Declare(
      googletest
      GIT_REPOSITORY https://github.com/google/googletest.git
      GIT_TAG v1.15.2
    )
    set(INSTALL_GTEST OFF CACHE BOOL "" FORCE)
    FetchContent_MakeAvailable(googletest)
  endif()
  if(TARGET gtest AND NOT TARGET GTest::gtest)
    add_library(GTest::gtest ALIAS gtest)
  endif()
  if(TARGET gtest_main AND NOT TARGET GTest::gtest_main)
    add_library(GTest::gtest_main ALIAS gtest_main)
  endif()
  if(TARGET GTest::gtest AND NOT TARGET Gtest::gtest)
    add_library(Gtest::gtest ALIAS GTest::gtest)
  endif()
  if(TARGET GTest::gtest_main AND NOT TARGET Gtest::gtest_main)
    add_library(Gtest::gtest_main ALIAS GTest::gtest_main)
  endif()
endfunction()
